python3: can't open file '/usr/src/app/./ps': [Errno 2] No such file or directory
python3: can't open file '/usr/src/app/./ps': [Errno 2] No such file or directory
python3: can't open file '/usr/src/app/./ps': [Errno 2] No such file or directory
python3: can't open file '/usr/src/app/./ps': [Errno 2] No such file or directory
INFO:     Started server process [1318]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11101 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1318]
INFO:     Started server process [1339]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     192.168.4.27:57865 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     192.168.4.27:57873 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1339]
INFO:     Started server process [1360]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:60190 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1360]
INFO:     Started server process [1433]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:45342 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     192.168.4.27:57927 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     192.168.4.27:57927 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1433]
INFO:     Started server process [1513]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:59280 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:46444 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:46452 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:46468 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:37288 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:37294 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     192.168.4.27:58314 - "GET /file/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59.json HTTP/1.1" 200 OK
/usr/data/ucd/official/湖北荆州原始数据--配网线路--第三批--4.14_2023-05-04_17-29-59.json
INFO:     192.168.4.27:58365 - "GET /ucd/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:37594 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:37596 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1513]
INFO:     Started server process [1592]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:36044 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:44188 - "GET /ucd/get_json_info/official/%E5%8F%98%E7%94%B5%E7%AB%99%E7%BC%BA%E9%99%B7%E6%A3%80%E6%B5%8B%E5%9B%BE_5.15_2023-05-16_11-05-04 HTTP/1.1" 200 OK
INFO:     127.0.0.1:44196 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:32776 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:32784 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:32788 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:32804 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40084 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40094 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40096 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40112 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40118 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40128 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40130 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40132 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40136 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40150 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40162 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40174 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40186 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40188 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40200 - "POST /ucd/add_tags HTTP/1.1" 422 Unprocessable Entity
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1592]
INFO:     Started server process [1669]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:37934 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:58836 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21 HTTP/1.1" 200 OK
INFO:     127.0.0.1:58846 - "POST /ucd/add_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 229, in add_tags_to_json
    json.dump(json_info, json_path)
  File "/usr/local/lib/python3.9/json/__init__.py", line 180, in dump
    fp.write(chunk)
AttributeError: 'str' object has no attribute 'write'
INFO:     Started server process [1739]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1789]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     127.0.0.1:54776 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     Started server process [1792]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1793]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1794]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1795]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1796]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1797]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1798]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1799]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     127.0.0.1:57696 - "GET /ucd/get_json_info/official/%E4%B8%AD%E6%A0%B8%E9%87%8D%E5%BA%86%E5%85%89%E4%BC%8F%E6%95%B0%E6%8D%AE%E5%B7%A1%E6%A3%80%E6%8B%8D%E6%91%84_%E7%BA%A2%E5%A4%96%E5%8F%AF%E8%A7%81%E5%85%89_2024-07-23_16-11-19 HTTP/1.1" 200 OK
INFO:     Started server process [1800]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     127.0.0.1:57712 - "POST /ucd/add_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 229, in add_tags_to_json
    json_file.dump(json_info, json_path)
  File "/usr/local/lib/python3.9/json/__init__.py", line 180, in dump
    fp.write(chunk)
AttributeError: 'str' object has no attribute 'write'
INFO:     Started server process [1801]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1802]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1803]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1804]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1805]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1806]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1807]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1830]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1880]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     127.0.0.1:40320 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     Started server process [1883]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1884]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1885]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1886]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 11106): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Started server process [1913]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:50896 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:43730 - "GET /ucd/get_json_info/official/%E5%8F%98%E7%94%B5%E7%AB%99%E7%BC%BA%E9%99%B7%E6%A3%80%E6%B5%8B%E5%9B%BE_5.15_2023-05-16_11-05-04 HTTP/1.1" 200 OK
INFO:     127.0.0.1:43738 - "POST /ucd/add_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 229, in add_tags_to_json
    json_file.dump(json_info, json_path)
AttributeError: '_io.TextIOWrapper' object has no attribute 'dump'
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1913]
INFO:     Started server process [1994]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:54050 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:36790 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:36804 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:54250 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     192.168.4.27:58840 - "GET /file/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42.json HTTP/1.1" 200 OK
INFO:     192.168.4.27:58868 - "GET /file/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42.json HTTP/1.1" 200 OK
INFO:     192.168.4.27:58919 - "GET /ucd/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42.json HTTP/1.1" 404 Not Found
/usr/data/ucd/official/新疆3月输电数据--喀什供电公司-220千伏喀伽二线_2023-03-22_19-14-42.json
INFO:     192.168.4.27:58934 - "GET /ucd/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:34424 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1994]
INFO:     Started server process [2072]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:44576 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:32850 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:37262 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:37264 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:59526 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:59528 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2072]
INFO:     Started server process [2151]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:57650 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:46780 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:46782 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:46786 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:38514 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:38528 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:38540 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:38542 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:38548 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:37950 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:37962 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:37976 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:37980 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:37990 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2151]
INFO:     Started server process [2229]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:11106 (Press CTRL+C to quit)
INFO:     127.0.0.1:46958 - "GET /ucd/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:58148 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:58160 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:58166 - "GET /ucd/get_json_info/official/%E5%8F%98%E7%94%B5%E7%AB%99%E7%BC%BA%E9%99%B7%E6%A3%80%E6%B5%8B%E5%9B%BE_5.15_2023-05-16_11-05-04 HTTP/1.1" 200 OK
INFO:     127.0.0.1:58170 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:41972 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41988 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:47598 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:47606 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:47620 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:47632 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:37996 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:38008 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:60902 - "GET /ucd/get_json_info/official/from_%E6%9D%8E%E6%80%9D%E8%AF%9A_%E5%B9%BF%E4%B8%9C%E6%B8%85%E8%BF%9C%E9%9B%86%E7%94%B5%E7%BA%BF%E8%B7%AF%E5%B7%A1%E6%A3%80_%E5%8F%AF%E8%A7%81%E5%85%89%E6%8B%8D%E6%91%84_2024-08-02_10-53-44 HTTP/1.1" 200 OK
INFO:     127.0.0.1:60910 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:60926 - "GET /ucd/get_json_info/official/%E7%83%9F%E7%81%AB%E5%90%88%E6%88%90%E8%A7%86%E9%A2%91%E2%80%94%E2%80%94%E5%9C%BA%E7%AB%99%E5%86%85%E6%95%B0%E6%8D%AE_2024-08-09_17-44-39 HTTP/1.1" 200 OK
INFO:     127.0.0.1:60934 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:49878 - "GET /ucd/get_json_info/official/%E5%86%80%E5%8C%97%E4%BF%9D%E5%AE%9A%E9%80%81%E6%A3%80%E6%95%B0%E6%8D%AE_2022%E5%B9%B408%E6%9C%88_2022-11-09_10-53-54 HTTP/1.1" 200 OK
INFO:     127.0.0.1:49884 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:49886 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:49896 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:56534 - "GET /ucd/get_json_info/official/%E5%8F%98%E7%94%B5%E7%AB%99%E7%BC%BA%E9%99%B7%E6%A3%80%E6%B5%8B%E5%9B%BE_5.15_2023-05-16_11-05-04 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56538 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:39618 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:39630 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:39644 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:39652 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:39662 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:39676 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:39690 - "GET /ucd/get_json_info/official/%E5%8F%98%E7%94%B5%E7%AB%99%E7%BC%BA%E9%99%B7%E6%A3%80%E6%B5%8B%E5%9B%BE_5.15_2023-05-16_11-05-04 HTTP/1.1" 200 OK
INFO:     127.0.0.1:39696 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:42542 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42556 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42564 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42574 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42590 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42594 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42606 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42608 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:41938 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E9%AA%8C%E7%94%B5_2023-06-30_15-43-00 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41944 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:41960 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41974 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:41988 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E9%AA%8C%E7%94%B5_2023-06-30_15-43-00 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42004 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:56542 - "GET /ucd/get_json_info/official/%E6%89%AC%E5%B7%9E%E9%AB%98%E9%82%AE%E6%95%B0%E6%8D%AE_test_2024-05-30_10-18-44 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56554 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:56562 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56570 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:56576 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56592 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:56602 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E9%AA%8C%E7%94%B5_2023-06-30_15-43-00 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56604 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:56616 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E-20230509-demo_fix_2023-05-09_20-27-58 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56624 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:55520 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E9%AA%8C%E7%94%B5_2023-06-30_15-43-00 HTTP/1.1" 200 OK
INFO:     127.0.0.1:55530 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:55538 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21 HTTP/1.1" 200 OK
INFO:     127.0.0.1:55540 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     192.168.4.27:60618 - "GET /ucd/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21.json HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:36878 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E9%AA%8C%E7%94%B5_2023-06-30_15-43-00 HTTP/1.1" 200 OK
INFO:     127.0.0.1:36884 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:57552 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21 HTTP/1.1" 200 OK
INFO:     127.0.0.1:57562 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     192.168.4.27:60657 - "GET /ucd/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21.json HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60358 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:60364 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:59698 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:59702 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:43454 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:43456 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:43458 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:43472 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:49904 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:49906 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:49918 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:49930 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:49942 - "GET /ucd/get_json_info/official/%E6%96%B0%E7%96%863%E6%9C%88%E8%BE%93%E7%94%B5%E6%95%B0%E6%8D%AE--%E5%96%80%E4%BB%80%E4%BE%9B%E7%94%B5%E5%85%AC%E5%8F%B8-220%E5%8D%83%E4%BC%8F%E5%96%80%E4%BC%BD%E4%BA%8C%E7%BA%BF_2023-03-22_19-14-42 HTTP/1.1" 200 OK
INFO:     127.0.0.1:49944 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:43260 - "GET /ucd/get_json_info/official/%E5%8F%98%E7%94%B5%E7%AB%99%E7%BC%BA%E9%99%B7%E6%A3%80%E6%B5%8B%E5%9B%BE_5.15_2023-05-16_11-05-04 HTTP/1.1" 200 OK
INFO:     127.0.0.1:43270 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:43280 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:43282 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:55798 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:55812 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:41038 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41044 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:41046 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41054 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:47762 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:47776 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:47786 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:47802 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:47806 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42972 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42986 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:43000 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:58264 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:58266 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:51976 - "POST /ucd/add_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:36088 - "GET /ucd/get_json_info/official/xj_bd_%E8%A1%A8%E8%AE%A1%E8%AF%86%E5%88%AB_2023-03-09_13-55-18 HTTP/1.1" 200 OK
INFO:     127.0.0.1:36100 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:36114 - "GET /ucd/get_json_info/official/%E6%B9%96%E5%8C%97%E8%8D%86%E5%B7%9E%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE--%E9%85%8D%E7%BD%91%E7%BA%BF%E8%B7%AF--%E7%AC%AC%E4%B8%89%E6%89%B9--4.14_2023-05-04_17-29-59 HTTP/1.1" 200 OK
INFO:     127.0.0.1:36116 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42396 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E9%AA%8C%E7%94%B5_2023-06-30_15-43-00 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42406 - "GET /ucd/get_tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:42418 - "GET /ucd/get_json_info/official/%E5%8C%97%E4%BA%AC%E9%A3%9E%E5%8D%8E_%E7%AC%AC%E5%9B%9B%E6%89%B9%E6%95%B0%E6%8D%AE_%E9%A9%AC%E7%94%B2_2023-06-05_15-30-21 HTTP/1.1" 200 OK
INFO:     127.0.0.1:42434 - "GET /ucd/get_tags HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/JoTools/../uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/code/app/dataset.py", line 252, in get_tags_from_json
    json_info = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
